export const SET_EDIT_ROW = "SET_EDIT_ROW";

export const TABLE_CHANGED = "TABLE_CHANGED";

export const PRODUCTS_LIST = "PRODUCTS_LIST";

export const DELETE_ROW = "DELETE_ROW";

export const EDIT_PRODUCT = "EDIT_PRODUCT";

export const ADD_PRODUCT = "ADD_PRODUCT";

export const SHOPPING_LIST = "SHOPPING_LIST";

export const CLEAR_SHOPPING_LIST = "CLEAR_SHOPPING_LIST";

export const DELETE_FROM_SHOPPPING_LIST = "DELETE_FROM_SHOPPPING_LIST";